// <auto-generated />
using System;
using DynatronCustomerCRUD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynatronCustomerCRUD.Migrations
{
    [DbContext(typeof(DynatronDbContext))]
    [Migration("20240117033639_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DynatronCustomerCRUD.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 16, 19, 36, 39, 233, DateTimeKind.Local).AddTicks(5206),
                            Email = "bobdillon@example.com",
                            FirstName = "Bob",
                            LastName = "Sclansky",
                            LastUpdatedDate = new DateTime(2024, 1, 16, 19, 36, 39, 233, DateTimeKind.Local).AddTicks(5252)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 16, 19, 36, 39, 233, DateTimeKind.Local).AddTicks(5253),
                            Email = "elroysmith@example.com",
                            FirstName = "Elroy",
                            LastName = "Smith",
                            LastUpdatedDate = new DateTime(2024, 1, 16, 19, 36, 39, 233, DateTimeKind.Local).AddTicks(5254)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 16, 19, 36, 39, 233, DateTimeKind.Local).AddTicks(5255),
                            Email = "taixiaoma@example.com",
                            FirstName = "Tai",
                            LastName = "Xiaoma",
                            LastUpdatedDate = new DateTime(2024, 1, 16, 19, 36, 39, 233, DateTimeKind.Local).AddTicks(5256)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 16, 19, 36, 39, 233, DateTimeKind.Local).AddTicks(5257),
                            Email = "kevinbacon@example.com",
                            FirstName = "Kevin",
                            LastName = "Bacon",
                            LastUpdatedDate = new DateTime(2024, 1, 16, 19, 36, 39, 233, DateTimeKind.Local).AddTicks(5258)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 16, 19, 36, 39, 233, DateTimeKind.Local).AddTicks(5259),
                            Email = "alenazarcovia@example.com",
                            FirstName = "Alena",
                            LastName = "Zarcovia",
                            LastUpdatedDate = new DateTime(2024, 1, 16, 19, 36, 39, 233, DateTimeKind.Local).AddTicks(5260)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
